### ISSUE TITLE
feature: revert change on 0.5.0 for backwards compatability

### ISSUE THREAD

**Issue by c43721** [typestack/class-transformer#995]
### Description
In version 0.5.0, there was a change to rename the methods `plainToClass`, `classToPlain` and `classToClass`. These changes ultimately made updating to the latest version difficult when using frameworks like @nestjs.

See <https://github.com/nestjs/nest/issues/8637> for more details on the issues this caused in nestjs.

### Proposed solution
Revert the changes in 0.5.0 (keeping the security updates, of course) and re-publish the package under `1.0.0` with those breaking changes. This would satisfy `sem-ver` and would help package managers know about a breaking change better. Currently, there's issues like #994 which are confused on this change.

### Alternative soltuion
Make the methods backwards compatable and add a `@deprecated` doc comment on the method and call the new method. This way, you could remove the methods in a future version (such as 1.0.0).

### Conclusion 
Ultimately, it makes sense to re-publish under 1.0.0 to conform to sem-ver and to give a better message to developers using `class-transformer` that there's a breaking change and that they should read the docs (or the changelog!) or to make a patch version with backwards compatable changes and mark them as deprecated. In both cases, you would preserve your new syntax and also help the developer experience while using this package.

**Comment by jakubnavratil** [comment]
In my case, there is fix in: https://github.com/typestack/class-transformer/commit/90feca36d2b44b6c66428ccef9402b13b58f7e2e released under 0.4.1 but breaks compatibility. 
I would gladly take release of 0.4.2 or 0.5.1+ that reverts that breaking change (or make those methods deprecated). Some tools depends on this being version 0.4, and I was upgrading to 0.4.1 and cause of breaking change I cant and also I cant use that fix.
Please, release some version without that breaking change, thanks.

**Comment by NoNameProvided** [comment]
Fixed in 0.5.1

**Comment by NoNameProvided** [comment]
Thanks for the report. The removal of those functions was published accidentally. I have re-added them as deprecated. 

> This would satisfy sem-ver and would help package managers know about a breaking change better. 

We do use SemVer, however since we did not reach 1.0 yet we can only publish breaking changes as minor versions. To prevent things from happening like this in the future, you can pin your version to `0.5.x`. 

I am not comfortable bumping the version to 1.0 yet, because the internals should be rewritten, which will probably clean up some unintended edge-cases some folk may depend on. Hopefully, time will come sooner when I can get around to do it.

**Comment by c43721** [comment]
Thank you so much. I'm interested in hearing about what you want rewritten and some unintentional edge cases that are known but not fixed, as I would like to see what room I have to commit!

Thanks again for the swift response, and a even greater thank you to maintaining and helping!

**Comment by dls314** [comment]
> Fixed in 0.5.1

Is it possible to also fix this in a 0.4.2?

Some transitive dependencies have used ^0.4.0 as their version selector and while 0.4.2 would fit that selector, 0.5.1 doesn't.
